[package]
name = "studio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg_boost = "1.0.0"
tests_bin = "1.0.0"